version: "3.8"
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: database
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    container_name: adminer_container
    ports:
      - 8080:8080
volumes:
  db: 